### PR TITLE
add normative content to the index page

### PR DESCRIPTION
**Pull request by nosvalds**
Need to add the new normative content page to the index so folks can access the page.﻿

### CODE REVIEW

**Review by amy-silcock — APPROVED** [review]
Looks good!

**Review by AudreyIATI — COMMENTED** [review]
Looks good to me, but let me know if I've missed anything.

**Comment by nosvalds** [comment]
@amy-silcock @AudreyIATI my only question is if you want it at the bottom of the list like I've added it in the PR.

**Comment by amy-silcock** [comment]
That's fine. We don't currently have a set ordering for the dev documentation pages

**Review by AudreyIATI — APPROVED** [review]

**Pull request merged**
